spring.application.name=Movies

# ==============================================================
# CONFIGURATION DU SERVEUR
# ==============================================================
# Définit le préfixe global pour tous vos contrôleurs (ex: /api/movies)
server.servlet.context-path=/api
server.port=8080


logging.level.org.springframework.security=DEBUG
# ==============================================================
# CONFIGURATION POSTGRESQL
# ==============================================================
# Remplacez 'nom_de_votre_db' par le nom réel de votre base
spring.datasource.url=jdbc:postgresql://localhost:5432/Movies
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# CONFIGURATION JPA / HIBERNATE
# ==============================================================
# 'update' permet de créer/modifier les tables automatiquement sans supprimer les données
spring.jpa.hibernate.ddl-auto=update


# Affiche les requêtes SQL dans la console (très utile pour le debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spécifie le dialecte pour optimiser les requêtes pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================================================
# GESTION DES FICHIERS (Vidéos/Reels)
# ==============================================================
# Pour Spring Boot 3.x
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB


# Autorise Tomcat à "avaler" les gros flux de données sans couper la connexion
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-post-size=-1



# Augmenter le timeout si l'upload est lent
server.connection-timeout=20000

# Pour éviter des erreurs si tu tentes de supprimer un fichier encore ouvert par le système
spring.mvc.pathmatch.matching-strategy=ant_path_matcher